### ISSUE TITLE
如果某个slot的diplay是armature的话，添加的blendfunc不生效

### ISSUE THREAD

**Issue by mthread** [DragonBones/DragonBonesCPP#102]
如题
是DBCCSlot::updateDisplayBlendMode函数里的 if (_childArmature) 条件放在  if (spriteDisplay) 条件里的原因吧？ 
我们自己的程序，把判断移出来之后blendfunc变为正常，但是我现在无法确定这个是bug还是因为特殊的设定。

**Comment by akdcl** [comment]
如果_childArmature为真的话，spriteDisplay是一定存在的，是什么情况下会使得spriteDisplay没有，_childArmature却存在？

**Comment by mthread** [comment]
![image](https://cloud.githubusercontent.com/assets/3423809/7316674/9033eab6-eaab-11e4-9bef-604dfb8a34a8.png)
配置文件是这样的时候，增强效果没有添加上

**Comment by mthread** [comment]
![image](https://cloud.githubusercontent.com/assets/3423809/7316834/fe3456da-eaac-11e4-92e7-445008904ce8.png)
这里CCArmature构造的时候设置的display，但是armature里的_display 只是一个node
这里的是Slot:updateSlotDisplay 的设置slot _display 的地方
![image](https://cloud.githubusercontent.com/assets/3423809/7316906/c007e2ea-eaad-11e4-8d10-9b2e7b3d24b2.png)

但是，DBSlot::updateDisplayBlendMode 里是判断display是否是一个sprite，符合sprite时候，才会对_childArmature 操作

**Comment by mthread** [comment]
![image](https://cloud.githubusercontent.com/assets/3423809/7317004/6f5477a4-eaae-11e4-88e7-12772ebf686b.png)

**Comment by akdcl** [comment]
原来如此，上次被修改成了node，导致这里出了问题，移出判断确实也是合理的
