### ISSUE TITLE
Latest version crashes when firing up

### ISSUE THREAD

**Issue by dreamxstudio** [DragonBones/DragonBonesCPP#117]
Previous version breaks on Visual Studio while firing up in debug mode.
## The warning is:  HEAP: Free Heap block XXXX modified at XXXX after it was freed ##
But latest version crashes anyway.
## The error is: In CCRef the reference count is none zero while freeing the pointer. And in AmatureDisplayContainer.cpp line 42, before  the EventDispatcher pointer is released, the address is already 0xfeeefeee. ##

Please solve the bug! It's fatal!

**Comment by akdcl** [comment]
The bug has been fixed.
