### ISSUE TITLE
Bones position broken with director->setContentScaleFactor

### ISSUE THREAD

**Issue by TankTheFrank** [DragonBones/DragonBonesCPP#126]
In c965e993c8eb9f04160f262fefc09e7265472426 the sample looks like this:
<img width="727" alt="c965e993c8eb9f04160f262fefc09e7265472426" src="https://cloud.githubusercontent.com/assets/558962/18626586/9cf87616-7e5e-11e6-9700-dc4dc4da5a4b.png">

Since 4961178662a85da0000f81a10798767588153e08:
<img width="730" alt="4961178662a85da0000f81a10798767588153e08" src="https://cloud.githubusercontent.com/assets/558962/18626595/ad30b854-7e5e-11e6-8ef9-da2ecd06849f.png">

This also breaks Ubbie and virtually any armature:
<img width="651" alt="1e8788eaefbdda58b9e44a17d9034165c91571d0" src="https://cloud.githubusercontent.com/assets/558962/18626611/c516ac08-7e5e-11e6-9251-5c35014f6761.png">

I also tried exporting the data again with 4.7.3 - looks exactly the same.

**Comment by TankTheFrank** [comment]
I was using director->setContentScaleFactor(2.0f)
With content scale 1 is fine but using a different content scale is broken from 4961178662a85da0000f81a10798767588153e08 onwards.

**Comment by TankTheFrank** [comment]
Using the CCSlot.cpp from c965e993c8eb9f04160f262fefc09e7265472426 fixes this content scale issue.

**Comment by akdcl** [comment]
The bug has been fixed from 40229727f5816ed8a5fef4363d393f9432546ee4.
Thanks :)
