### ISSUE TITLE
是否能够提供新的接口?

### ISSUE THREAD

**Issue by yongtaotang** [DragonBones/DragonBonesCPP#13]
是否能够提供一个结构可以跳转到某动画的指定帧播放?

**Comment by akdcl** [comment]
目前已经可以任意跳转到动画的指定位置了, 具体的可以查看这个例子
https://github.com/DragonBones/DragonBonesCPP/blob/master/Cocos2DX_3.x/Demos/classes/AnimationBaseTest.cpp
