### ISSUE TITLE
_soundEventManager 不应该用create来创建对象

### ISSUE THREAD

**Issue by djwshh** [DragonBones/DragonBonesCPP#137]
CCFactory::CCFactory() 
{
    if (!EventObject::_soundEventManager) 
    {
        EventObject::_soundEventManager = CCArmatureDisplay::create();
    }
}
CCArmatureDisplay create的对象autorelease。下一帧就会被释放，此处需要new或者调用次retain不然动画中如果有sound事件就会导致崩溃

**Comment by akdcl** [comment]
感谢，这个  bug 已经修复了
