### ISSUE TITLE
2 Demos doesn't work at all

### ISSUE THREAD

**Issue by aseem2625** [DragonBones/DragonBonesCPP#142]
Hi @superlancelot 
DragonBones 4.9.5
I've tried importing all demos . 3 got successfully imported. **But 2 of them don't work.**
Demos not working:
[Knight](https://github.com/DragonBones/DragonBonesCPP/tree/master/Cocos2DX_3.x/Demos/Resources/res/Knight)
[CoreElement](https://github.com/DragonBones/DragonBonesCPP/tree/master/Cocos2DX_3.x/Demos/Resources/res/CoreElement)

Here is screenshot on importing both projects.

![image](https://cloud.githubusercontent.com/assets/6055628/21290523/ec158894-c4e3-11e6-835d-a052cb4383ba.png)

![image](https://cloud.githubusercontent.com/assets/6055628/21290528/f6e33474-c4e3-11e6-9c61-3f823ae3ead9.png)

**Comment by superlancelot** [comment]
Everything looks correct in your screen, what's your point?

**Comment by aseem2625** [comment]
@superlancelot 
Neither of the animations is opening! Otherwise why will I report just 2 of the demos?
I clicked on the animations in Library but few have errors in them.
My screenshot tells that on opening these 2 animations, I got nothing on my screen doing whatsoever.

Please check by opening those 2 demos in DragonBones 4.9.5
