### ISSUE TITLE
When to release a new version of supporting DB 5.0 data format?

### ISSUE THREAD

**Issue by sosoayaen** [DragonBones/DragonBonesCPP#148]
什么时候推出支持 DB 5.0 版本数据格式的 runtime 呢，最近 DB 5.1 使用起来还是有很大的体验提升的，但是只能导出 4.5 版本的数据格式。还有 插槽 时间线层级变化貌似在 runtime 中还是有点问题，无法以正确的层级播放动画。

**Comment by akdcl** [comment]
因为其他开发任务，一直没法进行 cpp 版本的升级开发，目前 cpp 只能支持 4.5 的格式，所有 5.0 格式的特性都不能在 cpp 版本中使用，我们会想办法尽快将 cpp 升级到新的版本，不过恐怕暂时还不能给出准确的时间点，保守的估计要延后一个月左右

**Comment by sosoayaen** [comment]
了解了，辛苦 :+1:
