### ISSUE TITLE
呆锅，又crash鸟。（hi guys, it crashed agina!）

### ISSUE THREAD

**Issue by xiajiaonly** [DragonBones/DragonBonesCPP#154]
cocos2d 3.15.1 例子中的KnightGame，运行会crash。能严谨点嘛？开发呆锅？是要倒闭了吗？
系统win8.1 64bit，编译环境VS2013. 

Branch:Master

**Comment by jume2003** [comment]
不会!

**Comment by sosoayaen** [comment]
你这说话方式我就不爱看了，人家免费给你用，有本事你自己开发一个，或者自己把 crash 解决掉，没本事就边上吃瓜，或者态度好点儿。什么叫要倒闭了？说话前能不能过过脑子，这种话也好意思讲出来。

**Comment by xiajiaonly** [comment]
哇哈哈哈哈哈，又是“有本事”，又是“没本事的”。又是“免费”，又是“没脑子”的。又是边上“吃西瓜的”，呆锅，我是不是要谢主隆恩呀！哇哈哈哈哈哈哈。我just提个醒，也将不会使用这个东西，至少是这些年不会用到吧，也许以后某年会用到哦，只是例行编译测试一下，看看效果嘛，也不维护。毕竟这个功能的实现还是蛮多的嘛。
我这是处了逆鳞了嘛？好怕怕的样子呀。“没本事就闭嘴，免费的还啰嗦”。好怕怕哦。

**Comment by xiajiaonly** [comment]
呆锅：是“大哥”的方言版本哈，别误会了，并没有任何种族歧视或者反人类的意思哈。

**Comment by akdcl** [comment]
欢迎反馈问题，但请理性发言，这个 issue 没有什么有效的信息，暂时先关闭了。
可以尝试使用 dev 分支。

**Comment by xiajiaonly** [comment]
好吧，既然都这么严肃，那就言归正传吧。(幽默一下又不会怀孕)。
测试环境如下：cocos官方下载的版本，版本号位：cocos2d-x-3.15.1
DB代码使用官方Master分支的当前版本。编译工具为VS2013 update5，运行环境为：win8.1 64bit 专业版.
修改AppDelegate.cpp中53行左右，只加载场景KnightGame，如下：
auto scene = KnightGame::createScene();，其他场景加载代码注销。

Debug模式下编译运行crash窗口如下图：
![image](https://user-images.githubusercontent.com/4102643/29818600-9e5effa2-8cef-11e7-886c-0898f4fb781e.png)
跟踪代码，发现问题发生在Animation.cpp文件的321行。所在函数传入的参数animationName是通过层层引用传入的。但是在_fadeOut函数中，引用的对象已经失效(被回收)。造成后面对animationName的使用非法产生异常。
简单的修改方式为：修改AnimationState.h中118行的返回类型为值而非引用。修改之后程序可以正常运行。

**Comment by xiajiaonly** [comment]
@akdcl 详细描述如上。

**Comment by akdcl** [comment]
@xiajiaonly 非常感谢提供的调试信息：）
只是希望不要引起争执，我们会在近期发布 dev 到 master 来修复这些问题
