### ISSUE TITLE
5.0 对象池全部失效了

### ISSUE THREAD

**Issue by jareguo** [DragonBones/DragonBonesCPP#163]
在这个提交中 https://github.com/DragonBones/DragonBonesCPP/pull/152/commits/6e24d6b5e66a957089e52e232100bcdf90659072#diff-4c0efc2292e024e840d3a6e33e2f70f1

修改了 BaseObject.cpp 的 _returnObject 实现，原先搜索不到 classTypeIndex 会默认插入一个 vector（通过 std::map 的 [] operator）。现在改成 find 以后，完全不会插入了。导致对象池永远为空。

**Comment by jareguo** [comment]
看了下最新的代码，问题似乎仍未修复。

**Comment by akdcl** [comment]
Hi, 这个问题已经在 5.5 版本修复了，目前还不能同时维护多个版本，当新版本发布时，老版本暂时不再维护了，还望谅解

**Comment by jareguo** [comment]
好的谢谢
