### ISSUE TITLE
几个问题和希望能采纳的建议

### ISSUE THREAD

**Issue by scutXu** [DragonBones/DragonBonesCPP#166]
1）是否能够提供一些文档供开发者参考呢？dragonbone-runtime提供了若干个接口类，主要用于作为回调以及资源构建，但是却没有说明这些回调的含义，调用的时机，以及资源内存的管理方式。我发现有的对象需要由外部调用者释放（如IArmatureDisplay和Armature），有的则由dragonbone-runtime负责管理（如Slot和TextureAtlasData），这些都需要通过阅读源码来了解，实在不便。

2）demo是否存在内存泄漏的问题，CCArmatureDisplay对象似乎都没有被释放？

3）是否应该将一些计算隐藏在runtime sdk内部？如矩阵变换和蒙皮计算，对于外部调用者而言，只需在update时获取计算后的vertices和uv进行渲染即可，spine-runtime的实现即是如此。

对于以上几个问题，恳请你给我一些答复，即使一些内容没有纳入你的开发计划中，也请告诉我。谢谢

**Comment by akdcl** [comment]
很抱歉，我们正计划在未来几个月逐步完善文档和教程以及一些设计思路。
1）IArmatureDisplay.dispise 或 Armature.dispise 以及 factory.clear 是需要开发者手动释放的，对应的是释放实例和释放资源。（龙骨内部采用对象池来管理，所以内存没有真的释放，这里如果需要真正释放内存，还需要使用 BaseObject.clearPool）

2）可以看 dev 分支的 demo 目前没有发现内存泄露的问题，dev 分支会在本周正式发布到 master

3）龙骨的渲染都委托给针对渲染引擎的插槽来处理，比如 EgretSlot UnitySlot CCSlot 等，所有的渲染逻辑都会在这里执行，并且渲染都依赖渲染引擎，龙骨完全不会干预渲染，任何数据与渲染引擎不匹配的情况，都会在对应的渲染插槽中被转换成适合引擎使用的数据，龙骨-》插槽-》渲染引擎，这是龙骨的设计思路，这样能最大程度让龙骨的源码可以被移植到各个语言，被对接到各个引擎（龙骨不会动态合并插槽渲染，所以不能将整个骨架视为一个 mesh，而应该视为多个 submesh 的集合体，后续可能会加入动态合并 mesh 的功能）

**Comment by jareguo** [comment]
> 2）demo是否存在内存泄漏的问题，CCArmatureDisplay对象似乎都没有被释放？

内存泄露问题在 Creator 中也没看到过

**Comment by akdcl** [comment]
我们已经更新了文档了例子， cpp 的版本已经与 ts 和 c# 同步了，均支持最新的 dragonbonepro，很遗憾 cocoscreator 暂时还不支持，这需要触控的专业团队才能支持，所以暂时只能支持 cocos2dx。

**Comment by jareguo** [comment]
Creator 插件机制还不完善，先让我们来跟进吧，有空会安排人支持最新版。

**Comment by akdcl** [comment]
@jareguo 原来是官方团队啊，失敬失敬，那太好了，因为前几天特意研究了 Creator 支持 db 的方式，原本想按照 Unity 的支持方式来支持 Creator，发现还是有很多内部的东西不太清楚：）

**Comment by jareguo** [comment]
不用客气~~ Creator 内部的东西还不太透明……
