### ISSUE TITLE
Mesh crash

### ISSUE THREAD

**Issue by Harry09** [DragonBones/DragonBonesCPP#169]
I have armature with mesh and when I call play to animate, it crash in BaseTimelineState.cpp line 173 because of _timelineData is nullptr.

My suggestion is to add:
```cpp
if (!_timelineData)
	return;
```
or something similar.

**Comment by akdcl** [comment]
Hi, could you send this dragonbones files to me?
Because the crash shouldn't happen, it's strange.

**Comment by Harry09** [comment]
I used the example from DragonBones Pro "Sheep Ani" but on other mesh armatures it crash.
[Sheep Ani.zip](https://github.com/DragonBones/DragonBonesCPP/files/1506410/Sheep.Ani.zip)

**Comment by akdcl** [comment]
The bug has been fixed :)
