### ISSUE TITLE
请问龙骨从代码里面 哪个位置可以看出龙骨对应的版本号

### ISSUE THREAD

**Issue by lupin888** [DragonBones/DragonBonesCPP#171]
请问龙骨从代码里面 哪个位置可以看出龙骨对应的版本号

**Comment by akdcl** [comment]
可以从 DragonBones.VERSION 中获取
https://github.com/DragonBones/DragonBonesJS/blob/master/DragonBones/src/dragonBones/core/DragonBones.ts#L244
https://github.com/DragonBones/DragonBonesCPP/blob/master/DragonBones/src/dragonBones/core/DragonBones.h#L457
https://github.com/DragonBones/DragonBonesCPP/blob/master/DragonBones/src/dragonBones/core/DragonBones.cpp#L10
