### ISSUE TITLE
项目示例的工程文件能共享吗？

### ISSUE THREAD

**Issue by shanfl** [DragonBones/DragonBonesCPP#177]
尊敬的开发组，能共享示例的dragonbone项目工程文件吗？目前只有导出的内容，没有原始内容。我觉得还是共享下原始项目文件，便于更好的学习。谢谢

**Comment by doubleclip** [comment]
导出的是可以再导入的……（二进制格式除外）。你想编辑和看项目文件，再导入就行了。 可以看这篇文章： http://blog.dragonbones.com/cn/%E6%95%99%E7%A8%8B/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84%E9%BE%99%E9%AA%A8-%E5%AF%BC%E5%87%BA%E5%92%8C%E5%AF%BC%E5%85%A5.html

**Comment by shanfl** [comment]
感激回复
