### ISSUE TITLE
动画靠近屏幕边缘会有部分图片不显示。

### ISSUE THREAD

**Issue by CrazyKtW** [DragonBones/DragonBonesCPP#179]
cocos3.15版本，当动画靠近屏幕边缘时，动画的部分图片会隐藏。

**Comment by wbbtcool** [comment]
我也碰到了这个问题，3.15版本，骨骼切片从屏幕外进入场景，会在某个位置切片隐藏，但是马上就会恢复正常。感觉是某一帧没有渲染出来。
