### ISSUE TITLE
How do I remove a skeleton data from memory?

### ISSUE THREAD

**Issue by Harry09** [DragonBones/DragonBonesCPP#184]
Should I use `removeDragonBonesData` and `removeTextureAtlasData`?

If so how to use it?

**Comment by akdcl** [comment]
Hi, you could clear data by `factory.clear();`.
https://github.com/DragonBones/DragonBonesCPP/blob/master/Cocos2DX_3.x/Demos/Classes/PerformanceTest.h#L118

**Comment by Harry09** [comment]
I can't remove one armature?

**Comment by akdcl** [comment]
If you just want to delete one DragonBones Data, you could use `removeDragonBonesData` and `removeTextureAtlasData` like this:
```
data = factory.loadDragonBonesData(rawData);
factory.removeDragonBonesData(data.name);
```
or
```
factory.loadDragonBonesData(rawData, "customName");
factory.removeDragonBonesData("customName");
```
