### ISSUE TITLE
Reload armature data without removing it

### ISSUE THREAD

**Issue by Harry09** [DragonBones/DragonBonesCPP#185]
Is this possible to reload armature data without removing `ArmatureProxy`?

**Comment by akdcl** [comment]
Hi, 
There is a lot of work to be done to implement such a feature, usually only in the editor, or it seems like it's not worth the effort. You could refer to how the unity editor does this.

https://github.com/DragonBones/DragonBonesCSharp/blob/master/Unity/src/DragonBones/Editor/UnityEditor.cs#L240
https://github.com/DragonBones/DragonBonesCSharp/blob/master/Unity/src/DragonBones/Scripts/unity/UnityFactory.cs#L331
https://github.com/DragonBones/DragonBonesCSharp/blob/master/Unity/src/DragonBones/Scripts/unity/UnityFactory.cs#L190
https://github.com/DragonBones/DragonBonesCSharp/blob/master/Unity/src/DragonBones/Scripts/unity/UnityFactory.cs#L274-L275
