### ISSUE TITLE
Crash with SFML

### ISSUE THREAD

**Issue by Vovus27** [DragonBones/DragonBonesCPP#188]
Tried to load animation example from Cocos version to SFML version: mecha_1004d.
An error and crash occurred in this code:

(class SFMLDisplay)

void setColor(const sf::Color& color)
       {
              for (auto& vert : verticesDisplay) 
              {
                     vert.color = color;
              }
       }

![sfml_crash](https://user-images.githubusercontent.com/42742573/44665051-a55e6300-aa1d-11e8-8d01-6674d80f34fa.png)

**Comment by Harry09** [comment]
Show code in `main.cpp`

**Comment by Vovus27** [comment]
Here is my main.cpp:

#include <SFML/Graphics.hpp>
#include <dragonBones/SFMLFactory.h>
#include <dragonBones/SFMLArmatureDisplay.h>
#include <dragonBones/SFMLFactory.h>
#include <dragonBones/SFMLArmatureDisplay.h>

int main()
{
	sf::RenderWindow window(sf::VideoMode(1024, 768), "My window");

	dragonBones::SFMLFactory factory;

	sf::Texture texture;

	texture.loadFromFile("mecha_1004d/mecha_1004d_tex.png");

	factory.loadDragonBonesData("mecha_1004d/mecha_1004d_ske.json");
	factory.loadTextureAtlasData("mecha_1004d/mecha_1004d_tex.json", &texture);

	auto armatureDisplay = factory.buildArmatureDisplay("mecha_1004d");
	armatureDisplay->getAnimation()->play("walk");
	armatureDisplay->setPosition({ 512.f, 440.f });

	sf::Clock clock;

	while (window.isOpen())
	{
		float deltaTime = clock.restart().asSeconds();

		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}

		factory.update(deltaTime);

		window.clear();
		window.draw(*armatureDisplay);
		window.display();
	}

	return 0;
}

Also I tried base demo files, and this works fine:

	texture.loadFromFile("DragonBoy_tex.png");

	factory.loadDragonBonesData("DragonBoy_ske.json");
	factory.loadTextureAtlasData("DragonBoy_tex.json", &texture);

	auto armatureDisplay = factory.buildArmatureDisplay("Dragon");
	armatureDisplay->getAnimation()->play("walk");
	armatureDisplay->setPosition({ 512.f, 440.f });

**Comment by Vovus27** [comment]
After some changes in code, I got working expample, but the character is now without swords and without events.

SFML version:

![sfmldisplay_fix](https://user-images.githubusercontent.com/42742573/44717614-28d38f00-aac6-11e8-8b0d-f27aae70557f.png)

![sfmleventdispatcher_fix](https://user-images.githubusercontent.com/42742573/44717624-2f620680-aac6-11e8-83f2-91f23b58dde8.png)

This character in Cocos project:

![char_from_cocos](https://user-images.githubusercontent.com/42742573/44717835-d8a8fc80-aac6-11e8-8dfa-b47e06ac5d2c.png)

**Comment by Harry09** [comment]
I figured out what is the problem. My wrapper isn't supporting armature in armature. Fix should be tomorrow.

**Comment by Harry09** [comment]
Hey, I committed fix to `dev` branch.

**Comment by Vovus27** [comment]
My main.cpp is the same as yours. 
With the difference is that the resources are placed in a folder ("AnimationLayer").



/** @file AnimationLayer.cpp
** @author Piotr Krupa (piotrkrupa06@gmail.com)
** @license MIT License
**/

#include <SFML/Graphics.hpp>

#include <dragonBones/SFMLFactory.h>
#include <dragonBones/SFMLArmatureDisplay.h>


int main()
{
	sf::RenderWindow window(sf::VideoMode(1024, 768), "My window");
	window.setFramerateLimit(60);

	dragonBones::SFMLFactory factory;

	sf::Texture texture;
	texture.loadFromFile("AnimationLayer/mecha_1004d_tex.png");

	factory.loadDragonBonesData("AnimationLayer/mecha_1004d_ske.json");
	factory.loadTextureAtlasData("AnimationLayer/mecha_1004d_tex.json", &texture);

	dragonBones::SFMLArmatureDisplay armatureDisplay("mecha_1004d");
	armatureDisplay.getAnimation()->play("walk");
	armatureDisplay.setPosition({ 512.f, 440.f });
	armatureDisplay.getEventDispatcher()->addDBEventListener(dragonBones::EventObject::LOOP_COMPLETE, [&](dragonBones::EventObject* event) {

		auto attackState = armatureDisplay.getAnimation()->getState("attack_01");
		if (!attackState)
		{
			attackState = armatureDisplay.getAnimation()->fadeIn("attack_01", 0.1f, 1, 1);
			attackState->resetToPose = false;
			attackState->autoFadeOutTime = 0.1f;
			attackState->addBoneMask("chest");
			attackState->addBoneMask("effect_l");
			attackState->addBoneMask("effect_r");
		}
	});

	sf::Clock clock;

	while (window.isOpen())
	{
		float deltaTime = clock.restart().asSeconds();

		sf::Event event;
		while (window.pollEvent(event))
		{
			if (event.type == sf::Event::Closed)
				window.close();
		}

		factory.update(deltaTime);

		window.clear();
		window.draw(armatureDisplay);
		window.display();
	}

	return 0;
}

**Comment by Vovus27** [comment]
Maybe it's in the compiler?
I'm using Visual Studio Ultimate 2013.
Version 12.0.40629.00 Update 5

**Comment by Harry09** [comment]
Probably yes. I'm using VS 2017. Compiler in VS 2017 has got a lot of upgrades.

**Comment by Vovus27** [comment]
Ok, thanks! Maybe it's time to upgrade :)
