### ISSUE TITLE
怎么添加blendMode？

### ISSUE THREAD

**Issue by mthread** [DragonBones/DragonBonesCPP#65]
动画师那里用flash 做完，用一个插件导出  http://dragonbones.effecthub.com/
导出之后发现blendMode这个字段就没有了。是因为这个插件的问题嘛？
请问，你们有推荐的插件嘛？

**Comment by mthread** [comment]
@lite3  多次测试，和多个动画结果，GL ONE ,GL ONE 的效果可和flash上的效果保持一致的   
你可以测试一下

**Comment by lite3** [comment]
@mthread 已经修复了。

**Comment by mthread** [comment]
恩恩 收到
