### ISSUE TITLE
一个动画作为另一个的子节点，并且setChildArmature后释放报错

### ISSUE THREAD

**Issue by qiutaoleo** [DragonBones/DragonBonesCPP#70]
调用代码
local bone=self.body:getCCSlot("Layer_11")
	self.gy=db.buildArmatureNode("zf")
    self:add(self.gy)
   	bone:setChildArmature(self.gy:getArmature())
	self.gy:pos(100,100)
	self.gy:getAnimation():gotoAndPlay("stand", -1, -1, 0)

出错位置
DBCCArmatureNode::~DBCCArmatureNode()
{
#if (DRAGON_BONES_ENABLE_LUA == 1)
	unregisterFrameEventHandler();
	unregisterMovementEventHandler();
#endif // DRAGON_BONES_ENABLE_LUA

    if (_clock)
    {
        _clock->remove(this);
        _clock = nullptr;
    }

    if (_armature)
    {
        delete _armature;//《-----------------------崩溃后调试armature已经被释放掉了
        _armature = nullptr;
    }
}

是我的用法有问题么？

**Comment by qiutaoleo** [comment]
好吧，我已经大概找到问题了
如果把那个子动画add到scene上面，同样调用setChildArmature
会在这里报错
void DBCCSlot::disposeDisplayList()
{
    std::vector<cocos2d::Node*> releasedNodeList;
    
    for (size_t i = 0, l = _displayList.size(); i < l; ++i)
    {
        if (_displayList[i].second == DisplayType::DT_ARMATURE)
        {
            Armature *armature = static_cast<Armature*>(_displayList[i].first);
            
            if (armature)
            {
                armature->dispose();//《---------------------------------armature已经释放掉了
                delete armature;
                _displayList[i].first = NULL;
            }
        }
        else
        {
            cocos2d::Node *display = static_cast<cocos2d::Node*>(_displayList[i].first);
            
            if (display && std::find(releasedNodeList.cbegin(), releasedNodeList.cend(), display) == releasedNodeList.cend())
            {
                display->cleanup();
                display->release();
                releasedNodeList.push_back(display);
            }
        }
    }
    
    releasedNodeList.clear();
}

也就是说 作为display添加到slot后，Armature会被释放一次，而且如果ArmatureNode添加到了其他节点上也会被释放一次，然后就出问题了

那是不是ArmatureNode不添加到其他节点，只retain，再setChildArmature。但这样的话子动画就不会调用DBCCArmatureNode的析构了。

**Comment by qiutaoleo** [comment]
补充下，可以把子动画当一个image加上去
bone:setDisplayImage(self.gy)
addChild可加可不加了
但是，这样释放的时候会造成其他动画node release的时候出错

**Comment by lite3** [comment]
建议使用[replaceSlot](https://github.com/DragonBones/DragonBonesCPP/blob/refactoring/dragonbones%2Fcore%2FArmature.h#L85)

**Comment by qiutaoleo** [comment]
额，我现在是把CCDisplay取出来了，获取node的位置跟随移动的。不过动作好像慢一帧，但也满足要求了。
要求比较简单。
