### ISSUE TITLE
请问如何提高龙骨动画的性能？

### ISSUE THREAD

**Issue by Jennal** [DragonBones/DragonBonesCPP#72]
好像龙骨动画的性能并不高，我们测试官方的小绿龙，在iPad3上同时跑100个，帧数掉到了25帧左右，这是完全无法接受的。

不知道是动画本身复杂度的问题，还是播放框架的问题？动画制作的过程中，有没有什么需要注意的地方，可以提高性能的？代码上有没有什么缓存或者其他方式可以提高性能？

**Comment by akdcl** [comment]
我们已经为龙骨动画提供了动画缓存的接口, 性能已经成倍增加了, 具体可以参考这个事例 https://github.com/DragonBones/DragonBonesCPP/blob/master/Cocos2DX_3.x/Demos/classes/PerformanceTest.cpp#L101
