### ISSUE TITLE
zorder 排序

### ISSUE THREAD

**Issue by lite3** [DragonBones/DragonBonesCPP#84]
https://github.com/DragonBones/DragonBonesCPP/blob/refactoring/dragonbones%2Fcore%2FArmature.cpp#L321-L358

为什么是先remove，然后再add到最顶层，而不是直接`slot->addDisplayToContainer(_display, i);`

**Comment by lite3** [comment]
@akdcl

**Comment by akdcl** [comment]
当动画全是静态动画时，如果有显示对象离开显示列表后又回来，或交换到某个特定深度，确实是可以通过add到指定的深度来实现深度变换或排序，但是如果，整个armature里含有动态添加的slot时，尤其是这些slot希望插入到某些静态slot之间，那么整个显示列表的排序则完全不是动画之前的排序，比如原来的是AB（12 渲染引擎Z）变成了ACDB（1234 渲染引擎Z）（1 1.4 1.5 2 dragonbonesZ），很明显addDisplayToContainer是针对渲染引擎的，此时如果B从显示列表移除后如果被插回为2，则会导致顺序混乱，目前比较简单的做法就是，当有显示对象重新被插入显示列表后，按照dragonbones的z，重排整个显示列表，这里具体的可以做优化，不过应该是单独针对每一个渲染平台，所以比较好的解决办法是在dbccarmature里override排序方法

**Comment by lite3** [comment]
哦
