### ISSUE TITLE
lua 回调参数修改

### ISSUE THREAD

**Issue by lite3** [DragonBones/DragonBonesCPP#85]
DBCPP 现在lua事件回调直接将参数列表作为回调函数的参数列表，这样的缺点是想要增加参数就需要再向参数列表末尾添加，会打乱参数的优先级，比如后面要添加Armature的参数就要放到最后，但是这是一个重要参数。
~~~ lua
-- @param db.DBCCArmatureNode armatureNode
-- @param int movementType
-- @param string movementId
-- @param bool isLastMovementId
local function onMovementEvent( armatureNode, movementType, movementID, isLastMovementId)
    
end
-- @param db.DBCCArmatureNode armatureNode
-- @param int movementType
-- @param string movementId
-- @param string frameLabel
local function onFrameEvent( armatureNode, movementType, movementID, frameLabel )
    
end
armatureNode:registerMovementEventHandler(onMovementEvent)
armatureNode:registerFrameEventHandler(onFrameEvent)
~~~

修改参数形式，将所有参数封装到一个table中，那么后续添加参数会很方便，也不影响现有的代码。

~~~ lua
-- @param table event
--  db.DBCCArmature armature
--  db.DBCCArmatureNode armatureNode
--  int type
--  string boneName
--  string movementId
--  string frameLabel
--  bool isLastMovementId
local function onEvent( event )
    
end
armatureNode:registerMovementEventHandler(onEvent)
armatureNode:registerFrameEventHandler(onEvent)
~~~
 
大家看这个table 中属性名是否需要修改，如果不修改过段时间我会提交上去。

**Comment by zrong** [comment]
同意。这样修改很好。

**Comment by lite3** [comment]
`movementId` 和 `isLastMovementId`  这两个参数名是否需要修改？

**Comment by zrong** [comment]
和 AS 版本统一么？

On Tue, Feb 3, 2015 at 12:21 AM, lite3 <notifications@github.com> wrote:

> movementId 和 isLastMovementId 这两个参数名是否需要修改？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonBones/DragonBonesCPP/issues/85#issuecomment-72485642>
> .
>



-- 
============================
曾嵘/Jacky Tsang
Blog:http://zengrong.net

**Comment by lite3** [comment]
这个其实是看cocos里的，其他的没看过，刚看了AS版本，说`movementId`不推荐用了，用`animationState`代替？

**Comment by zrong** [comment]
我个人感觉应该和 AS3 版本完全相同。毕竟 AS3 是源头。保持通用的 API 也方便移植。

2015-02-03 10:17 GMT+08:00 lite3 <notifications@github.com>:

> 这个其实是看cocos里的，其他的没看过，刚看了AS版本，说movementId不推荐用了，用animationState代替？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DragonBones/DragonBonesCPP/issues/85#issuecomment-72580145>
> .
>



-- 
============================
曾嵘/Jacky Tsang
Blog:http://zengrong.net

**Comment by lite3** [comment]
`movementId`    ->  `animationName`
`isLastMovementId`   ->  `isLastAnimation`

修改这两个属性名，其他不变，OK？

**Comment by akdcl** [comment]
同意，建议弱化movement，animation和movement同时存在会引起误解

**Comment by lite3** [comment]
如果要弱化movement就把lua注册事件也修改下。

`armatureNode:registerMovementEventHandler(onMovementEvent)`
->
`armatureNode:registerAnimationEventHandler(onMovementEvent)`

这样OK？

**Comment by akdcl** [comment]
同意

**Comment by superlancelot** [comment]
同意：）

**Comment by lite3** [comment]
现在变成这样了。
~~~ lua
-- @param table event
--  db.DBCCArmature armature
--  db.DBCCArmatureNode armatureNode
--  int movementType
--  string boneName
--  string animationName
--  string frameLabel
--  bool isLastAnimation
local function onEvent( event )
    
end
armatureNode:registerAnimationEventHandler(onEvent)
armatureNode:registerFrameEventHandler(onEvent)
~~~
