### ISSUE TITLE
A動畫 到 B動畫閃爍問題

### ISSUE THREAD

**Issue by sianzain** [DragonBones/DragonBonesCPP#95]
gotoAndPlay中 沒有更新Bone 跟 Slot設置
在CCDragonBones::update之前
Cocos2dxDisplayBridge被更新導致閃爍

**Comment by akdcl** [comment]
我们已经提供了新的cpp运行时, 不过仅支持cocos2d-x_3.x版本,所有类似的问题都会在这个版本被修复.
